server:
  port: ${FLUX_MCP_SERVER_PORT:${SERVER_PORT:8092}}

spring:
  threads:
    virtual:
      enabled: true

  r2dbc:
    url: ${FLUX_MCP_R2DBC_URL:${APP_R2DBC_URL:r2dbc:postgresql://192.168.9.148:5442/flux_mcp}}
    username: ${FLUX_MCP_DB_USERNAME:${APP_DATASOURCE_USERNAME:postgres}}
    password: ${FLUX_MCP_DB_PASSWORD:${APP_DATASOURCE_PASSWORD:123456}}

  flyway:
    url: ${FLUX_MCP_JDBC_URL:${APP_DATASOURCE_URL:jdbc:postgresql://192.168.9.148:5442/flux_mcp}}
    user: ${FLUX_MCP_DB_USERNAME:${APP_DATASOURCE_USERNAME:postgres}}
    password: ${FLUX_MCP_DB_PASSWORD:${APP_DATASOURCE_PASSWORD:123456}}


logging:
  level:
    "[com.silver.ai.fluxmcp]": DEBUG

app:
  mcp:
    session:
      store-type: ${FLUX_MCP_SESSION_STORE_TYPE:${APP_MCP_SESSION_STORE_TYPE:redis}}

redis:
  sdk:
    config:
      host: ${FLUX_MCP_REDIS_HOST:${APP_REDIS_HOST:192.168.9.148}}
      port: ${FLUX_MCP_REDIS_PORT:${APP_REDIS_PORT:6379}}
      password: ${FLUX_MCP_REDIS_PASSWORD:${APP_REDIS_PASSWORD:enbo123456?}}
